### ISSUE TITLE
Error: ENOENT: no such file or directory, chmod '..\dist\robots.txt'

### ISSUE THREAD

**Issue by ggarg2** [patrickmichalina/fusebox-angular-universal-starter#118] opened 2017-08-30 21:33 UTC
Hi @patrickmichalina 

Sometimes I am getting this error after running npm start. 

> fusebox-angular-universal-starter@0.0.0-development start E:\dev\fusebox-angular-universal-starter
> ts-node fuse.ts serve --build-type dev --env-config dev

 Launch "serve"
(node:11992) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
 Launch "clean"
 Launch "web"
→Copy to ./dist
Error: ENOENT: no such file or directory, chmod 'E:\dev\fusebox-angular-universal-starter\dist\robots.txt'

**Comment by patrickmichalina** [comment] 2017-08-31 03:26
I had this too on a Heroku build. It went away once I cleaned node cache and started fresh.

**Comment by ggarg2** [comment] 2017-08-31 06:37
i did the same but still i am getting these errors frequently

**Comment by patrickmichalina** [comment] 2017-08-31 13:20
What version of Node are you using?

**Comment by ggarg2** [comment] 2017-09-01 19:36
node -v 8.1.4
npm -v 5.3.0

**Comment by patrickmichalina** [comment] 2017-09-03 19:22
This is happening to me too. Not sure what the issue is yet, but will investigate.

**Comment by igorls** [comment] 2017-09-16 07:10
Hey, what's the status on this issue? Any way I could help?

**Comment by patrickmichalina** [comment] 2017-09-16 14:44
@igorls i haven't had time to investigate this. I might get to it sometime next week. If you could figure it out that would be awesome. I think its some sort of race condition in the build...

**Comment by patrickmichalina** [comment] 2017-09-16 16:01
@igorls i think my latest commit may have fixed it, but cannot reproduce. Let me know!

**Comment by igorls** [comment] 2017-09-17 07:31
@patrickmichalina Good work man! I've tested the latest build and it worked most of the times, it's still eventually occurring on production mode.. trying to investigate why, as you said no exact way to reproduce

**Comment by patrickmichalina** [comment] 2017-09-17 17:06
ok thanks I saw it a couple times too. I think i will ad some sort of delay to the step.... grrr

**Comment by igorls** [comment] 2017-09-17 22:27
well, now I'm getting the same chmod issue with another file
```
> ts-node fuse.ts serve --build-type prod --env-config=prod

 Launch "serve"
 Launch "clean"
 Launch "mk-dist"
 Launch "changelog"
 Launch "web"
→Copy to ./dist
Error: ENOENT: no such file or directory, chmod 'H:\ENTROPIA\fusebox-angular-universal-starter\dist\ping.html'
```

**Comment by ggarg2** [comment] 2017-09-19 14:22
Hi @patrickmichalina 

This issue is very serious. I am not able to start my project.

E:\dev\fusebox-angular-universal-starter>npm start

> fusebox-angular-universal-starter@0.0.0-development start E:\dev\fusebox-angular-universal-starter
> ts-node fuse.ts serve --build-type dev --env-config dev

 Launch "serve"
 Launch "clean"
 Launch "mk-dist"
 Launch "changelog"
 Launch "web"
→Copy to ./dist
Error: EPERM: operation not permitted, open 'E:\dev\fusebox-angular-universal-starter\dist\robots.txt'

**Comment by patrickmichalina** [comment] 2017-09-19 14:28
@ggarg2 yes you are right, I will try again today, thanks

**Comment by ggarg2** [comment] 2017-09-19 15:39
Hi @patrickmichalina 

i did few changes in web.ts. please have a look. After this change i didn't get  this error

Sparky.task(taskName(__filename), () =>{
    setTimeout(() => {
      Sparky.src('**', { base: `${BUILD_CONFIG.toolsDir}/web` })
      .dest(`./${BUILD_CONFIG.outputDir}`)
    }, 1000)
  })

**Comment by patrickmichalina** [comment] 2017-09-19 16:43
@ggarg2 please try the latest PR

```js
Sparky.task(taskName(__filename), () =>
  Sparky.src('web/**/*.*', { base: `${BUILD_CONFIG.toolsDir}` })
    .dest(`./${BUILD_CONFIG.outputDir}`))

```

if it doesn't work, will use the setTimeout method :)

**Comment by ggarg2** [comment] 2017-09-19 16:46
Sure i will try :)

**Comment by ggarg2** [comment] 2017-09-20 15:50
Hey is they any way to contact you? I have prepared dashboard code in this project but facing some issues. Please have a look at attached image
![2017-09-20 1](https://user-images.githubusercontent.com/6575592/30654083-81b18dea-9e4a-11e7-95c1-a066a207f76e.png)

**Comment by patrickmichalina** [comment] 2017-09-20 16:06
@ggarg2 looking nice, setting up a gitter here

https://gitter.im/fusebox-angular-universal-starter/Lobby#

**Comment by ggarg2** [comment] 2017-09-20 16:56
It is also working on small screens

![2017-09-20 2](https://user-images.githubusercontent.com/6575592/30656756-bd075142-9e52-11e7-91eb-0bfc4f37ce62.png)

**Comment by patrickmichalina** [comment] 2017-09-22 14:28
closing this, if it happens again please let us know

**Closed as completed by patrickmichalina** 2017-09-22 14:28 UTC
Labels: bug, help wanted, build-tools
