### ISSUE TITLE
Not able to start server in production mode

### ISSUE THREAD

**Issue by ggarg2** [patrickmichalina/fusebox-angular-universal-starter#108] opened 2017-08-28 06:55 UTC
Hi,

i am getting one issue when i am running this command npm run start.prod
```js
{"name":"Angular Universal App","type":"app","hostname":"goku","pid":14724,"level":50,"err":{"msg":"Uncaught (in promise): Error: Cannot find module './js/bundle-home.module.js'\nError: Cannot find module './js/bundle-home.module.js'\n    at Function.Module._resolveFilename (module.js:485:15)\n    at Function.Module._load (module.js:437:25)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at s (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:1793)\n    at c (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:2842)\n    at Function.r.import (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:3747)\n    at E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:891:29\n    at new ZoneAwarePromise (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:861:29)\n    at loadChildren (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:888:51)\n    at RouterConfigLoader.loadModuleFactory (E:\\dev\\fusebox-angular-universal-starter\\packages\\router\\src\\router_config_loader.ts:61:1)\n    at RouterConfigLoader.load (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:4057:52)\n    at MergeMapSubscriber.project (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:1835:74)\n    at MergeMapSubscriber._tryNext (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:125:21)\n    at MergeMapSubscriber._next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:115:12)\n    at MergeMapSubscriber.Subscriber.next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\Subscriber.ts:95:12)","url":"/","stack":"Function.Module._resolveFilename()@module.js:485:15\nFunction.Module._load()@module.js:437:25\nModule.require()@module.js:513:17\nrequire()@internal/module.js:11:18\ns()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:1793\nc()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:2842\nFunction.r.import()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:3747\n{anonymous}()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:891:29\nnew ZoneAwarePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:861:29\nloadChildren()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:888:51\nRouterConfigLoader.loadModuleFactory()@E:\\dev\\fusebox-angular-universal-starter\\packages\\router\\src\\router_config_loader.ts:61:1\nRouterConfigLoader.load()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:4057:52\nMergeMapSubscriber.project()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:1835:74\nMergeMapSubscriber._tryNext()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:125:21\nMergeMapSubscriber._next()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:115:12\nMergeMapSubscriber.Subscriber.next()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\Subscriber.ts:95:12\nresolvePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:795:31\nresolvePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:766:17\n{anonymous}()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:844:17\nZoneDelegate.invokeTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:425:31"},"msg":"Uncaught (in promise): Error: Cannot find module './js/bundle-home.module.js'\nError: Cannot find module './js/bundle-home.module.js'\n    at Function.Module._resolveFilename (module.js:485:15)\n    at Function.Module._load (module.js:437:25)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at s (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:1793)\n    at c (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:2842)\n    at Function.r.import (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1345:3747)\n    at E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:891:29\n    at new ZoneAwarePromise (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:861:29)\n    at loadChildren (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:888:51)\n    at RouterConfigLoader.loadModuleFactory (E:\\dev\\fusebox-angular-universal-starter\\packages\\router\\src\\router_config_loader.ts:61:1)\n    at RouterConfigLoader.load (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:4057:52)\n    at MergeMapSubscriber.project (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:1835:74)\n    at MergeMapSubscriber._tryNext (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:125:21)\n    at MergeMapSubscriber._next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:115:12)\n    at MergeMapSubscriber.Subscriber.next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\Subscriber.ts:95:12)","time":"2017-08-28T06:53:18.369Z","v":0}
[Browsersync] Proxying: http://localhost:8083
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:8000
    External: http://192.168.0.109:8000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.109:3001
```

**Comment by patrickmichalina** [comment] 2017-08-28 13:27
Thanks for reporting this! I think I know what the issue is, will try to figure it out today

**Comment by patrickmichalina** [comment] 2017-08-29 02:14
@ggarg2 thanks again! This was a pretty serious issue, fixed in this commit:

https://github.com/patrickmichalina/fusebox-angular-universal-starter/commit/3bf37e505c71f2b3d12d144744d4138b4c8497b5

**Comment by ggarg2** [comment] 2017-08-29 18:05
Now i am getting this issue.

{"name":"Angular Universal App","type":"app","hostname":"goku","pid":13536,"level":50,"err":{"msg":"Uncaught (in promise): Error: Cannot find module './js/bundle-home.module.js'\nError: Cannot find module './js/bundle-home.module.js'\n    at Function.Module._resolveFilename (module.js:485:15)\n    at Function.Module._load (module.js:437:25)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at s (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:1793)\n    at c (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:2842)\n    at Function.r.import (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:3747)\n    at E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:884:29\n    at new ZoneAwarePromise (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:861:29)\n    at loadChildren (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:881:51)\n    at RouterConfigLoader.loadModuleFactory (E:\\dev\\fusebox-angular-universal-starter\\packages\\router\\src\\router_config_loader.ts:61:1)\n    at RouterConfigLoader.load (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:4057:52)\n    at MergeMapSubscriber.project (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:1835:74)\n    at MergeMapSubscriber._tryNext (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:125:21)\n    at MergeMapSubscriber._next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:115:12)\n    at MergeMapSubscriber.Subscriber.next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\Subscriber.ts:95:12)","url":"/","stack":"Function.Module._resolveFilename()@module.js:485:15\nFunction.Module._load()@module.js:437:25\nModule.require()@module.js:513:17\nrequire()@internal/module.js:11:18\ns()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:1793\nc()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:2842\nFunction.r.import()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:3747\n{anonymous}()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:884:29\nnew ZoneAwarePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:861:29\nloadChildren()@E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:881:51\nRouterConfigLoader.loadModuleFactory()@E:\\dev\\fusebox-angular-universal-starter\\packages\\router\\src\\router_config_loader.ts:61:1\nRouterConfigLoader.load()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:4057:52\nMergeMapSubscriber.project()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:1835:74\nMergeMapSubscriber._tryNext()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:125:21\nMergeMapSubscriber._next()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:115:12\nMergeMapSubscriber.Subscriber.next()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\Subscriber.ts:95:12\nresolvePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:795:31\nresolvePromise()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:766:17\n{anonymous}()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:844:17\nZoneDelegate.invokeTask()@E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:425:31"},"msg":"Uncaught (in promise): Error: Cannot find module './js/bundle-home.module.js'\nError: Cannot find module './js/bundle-home.module.js'\n    at Function.Module._resolveFilename (module.js:485:15)\n    at Function.Module._load (module.js:437:25)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at s (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:1793)\n    at c (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:2842)\n    at Function.r.import (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:1351:3747)\n    at E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:884:29\n    at new ZoneAwarePromise (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\zone.js\\dist\\zone-node.js:861:29)\n    at loadChildren (E:\\dev\\fusebox-angular-universal-starter\\dist\\server.js:881:51)\n    at RouterConfigLoader.loadModuleFactory (E:\\dev\\fusebox-angular-universal-starter\\packages\\router\\src\\router_config_loader.ts:61:1)\n    at RouterConfigLoader.load (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:4057:52)\n    at MergeMapSubscriber.project (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\@angular\\router\\bundles\\router.umd.js:1835:74)\n    at MergeMapSubscriber._tryNext (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:125:21)\n    at MergeMapSubscriber._next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\operator\\mergeMap.ts:115:12)\n    at MergeMapSubscriber.Subscriber.next (E:\\dev\\fusebox-angular-universal-starter\\node_modules\\rxjs\\src\\Subscriber.ts:95:12)","time":"2017-08-29T18:02:37.639Z","v":0}

**Comment by patrickmichalina** [comment] 2017-08-29 18:06
@ggarg2 can you delete you .fusebox folder and try again?

**Comment by ggarg2** [comment] 2017-08-29 18:09
I deleted .fusebox folder and now it is working.

What is an issue ?

First i ran npm start
then i ran npm run start.prod and i was getting error.

But after deleting .fusebox folder.....i ran npm run start.prod command ....production server is working.

**Comment by patrickmichalina** [comment] 2017-08-29 18:10
@ggarg2 it won't happen again. I updated a plugin, and fusebox isn't always smart enough to bust its own plugin cache.

**Comment by ggarg2** [comment] 2017-08-29 18:13
Okay Awesome 👍

**Comment by ggarg2** [comment] 2017-09-05 17:35
Hi @patrickmichalina ,

I am facing the same issue in fresh project. I am able to run project in production mode only after deleting the fusebox folder.

**Comment by patrickmichalina** [comment] 2017-09-05 17:42
@ggarg2 ok thanks, I will check out using a fresh project.

**Comment by ggarg2** [comment] 2017-09-05 17:44
Let me give you steps. 
First git clone
npm install
npm start
npm run start.prod

**Comment by patrickmichalina** [comment] 2017-09-05 17:46
I think I know what is happening in general... Basically, in prod mode, we get a hash of the file in order to bust a CDN cache in production. I think, the fusebox system is caching references. I will try to get this resolved today, thanks again for the info.

**Comment by ggarg2** [comment] 2017-09-05 17:54
One more thing i am seeing at cmd. Page routing stopped working but after reloading the page everything is working,

killing worker{"name":"Angular Universal App","type":"http-access","hostname":"goku","pid":7440,"req_id":"5086b290-9260-11e7-8a4d-fb5265fcf5c3","level":30,"res":{"statusCode":304,"header":"HTTP/1.1 304 Not Modified\r\nX-Powered-By: Express\r\nX-Request-Id: 5086b290-9260-11e7-8a4d-fb5265fcf5c3\r\nETag: W/\"40f0-qi+b6p7VwvvV03KWBr8XIWEdbIQ\"\r\nDate: Tue, 05 Sep 2017 17:33:22 GMT\r\nConnection: close\r\n\r\n"},"duration":30.560643,"req":{"method":"GET","url":"/","headers":{"if-none-match":"W/\"40f0-qi+b6p7VwvvV03KWBr8XIWEdbIQ\"","accept-language":"en-GB,en-US;q=0.8,en;q=0.6","accept-encoding":"identity","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","upgrade-insecure-requests":"1","cache-control":"max-age=0","connection":"close","host":"localhost:8083"},"query":{}},"msg":"request finish","time":"2017-09-05T17:33:22.392Z","v":0}

**Closed as completed** 2017-09-05 21:58 UTC
Labels: bug

**Comment by patrickmichalina** [comment] 2017-09-05 22:14
@ggarg2 this should be fixed, lemme know if it happens again

**Comment by ggarg2** [comment] 2017-09-06 20:06
Sure i will test and let you know
